<?php

// autoload_real.php @generated by Composer

class ComposerAutoloaderInit995f814905ed5c0e73a90660448252c5
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('WooCommerceCategorySlider\Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    /**
     * @return \WooCommerceCategorySlider\Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        require __DIR__ . '/platform_check.php';

        spl_autoload_register(array('ComposerAutoloaderInit995f814905ed5c0e73a90660448252c5', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \WooCommerceCategorySlider\Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('ComposerAutoloaderInit995f814905ed5c0e73a90660448252c5', 'loadClassLoader'));

        require __DIR__ . '/autoload_static.php';
        call_user_func(\WooCommerceCategorySlider\Composer\Autoload\ComposerStaticInit995f814905ed5c0e73a90660448252c5::getInitializer($loader));

        $loader->setClassMapAuthoritative(true);
        $loader->register(true);

        return $loader;
    }
}
